spring.application.name=App
# ==================== SERVER ====================
server.port=8080

# ==================== H2 DATABASE ====================
spring.datasource.url=jdbc:h2:mem:ticketdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true

# H2 Console (accessible at http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==================== EMAIL (Mailtrap) ====================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=63e47729154553
spring.mail.password=834016e7fa1747
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==================== SECURITY ====================
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN